[filters]
excluded_subject_ids = []
auto_excluded_subject_ids = [
    332677, # 贝里琉岛 -乐园的格尔尼卡
    363612, # 沙盒
    414861, # Future Kid Takara
    473414, # 永远的大和号 REBEL3199 第四章 水色的少女
    473415, # 永远的大和号 REBEL3199 第五章 白热的银河大战
    473416, # 永远的大和号 REBEL3199 第六章 碧蓝迷宫
    487782, # 新劇場版☆ケロロ軍曹 復活して速攻地球滅亡の危機であります！
    501729, # 剧场版 魔法科高校的劣等生 四叶继承篇
    505562, # 剧场版 物怪 蛇神
    532053, # 地球大好き！きっくん
    532772, # クマーバ シーズン3
    534907, # IDOLiSH7-偶像星愿- 剧场总集篇 前篇
    545844, # 电影 角落小伙伴 天空王国与两位小伙伴
    552670, # 烟囱小镇的普佩 〜约定的钟楼〜
    555683, # IDOLiSH7-偶像星愿- 剧场总集篇 后篇
    562099, # 谁是窃书之人
    570330, # 怪物弹珠 DEADVERSE RELOADED
    576343, # ほっぺちゃん ～サン王国と黒ほっぺ団の秘密～
    576669, # 绽放的巴黎之星
    578275, # 後朝の花雪
    580446, # 越辙而行
    580762, # 住在神奈川的精灵
    581987, # JOCHUM 第2季
    582598, # ねずみくんのチョッキ
    582915, # 涩谷♡八 第四部分
    583974, # 小泉八云的怪谈世界
    585457, # 森林家族 芙蕾雅的奇妙时光
    588026, # アニラとココラ
    588231, # 「LIMIT ZERO BREAKERS」世界観PV世界は救わない。自らを救う物語。(Full ver.)
    588612, # 2200年猫之国日本
    589793, # うそ探偵トマント ベジフル“プチっ”と情報編
    590629, # Mafiosa
    591455, # 雀魂 X 银魂 联动动画PV
    596843, # 聖女なのに国を追い出されたので、崩壊寸前の隣国へ来ました シーズン2
    598053, # 微かな夕阳 / 魔法少女ホロウィッチ！
    599919, # Run Run Lantern
    600956, # 「人生讚歌」Official Music Video
    601763, # 你还是不懂群马～令和版～
    602943, # 宇宙涅槃
    604330, # 《藤本树17-26》Part-1
    604331, # 《藤本树17-26》Part-2
    605312, # おしり前マン〜復活のおしり前帝国〜
    607043, # 小3阿贝 QQ小芝麻
    609741, # バトルヒロインの日常～愛天使世紀ウェディングアップル～
    609915, # Tokyo Nightscape
    610350, # 黄金神威 札幌啤酒工厂篇 前篇
    610359, # 黄金神威 札幌啤酒工厂篇 后篇
    611768, # 电影秘密的偶像公主
    612697, # 铠真传 武士军团 第2部分
    613025, # 迷失的万圣节：十年之后
    613380, # そろ谷のけいばっち シーズン3
    613815, # 奔向太阳
    615446, # 电影蜡笔小新：奇奇怪怪！我的妖怪假期
    616378, # 小鲨鱼去郊游 第二季
    616383, # 《新世纪福音战士》30周年纪念特别放映
    616392, # 【汐塔】《云海逐鲸》
    616616, # 百姓贵族 第四季
    617004, # CHOPPER’s
    617321, # 今日をしるして
    617947, # 为了共同闪耀的明天
    618661, # ゲルぴよ
    619052, # 做得很好！名作君 完全新作
    619136, # 能登半島復興応援企画
    619321, # 「花の芥 -Re;bloom-」 告知アニメPV
    619447, # シルベ
    619911, # 托尼托尼·乔巴
    620064, # 如果烧陶的话也做个马克杯吧 二番窑 剧场总集篇
    620410, # THE RUN.
    620584, # 「Q.E.D.」MV
    620741, # 黑猫警长——人工智能安全篇
    620918, # NEEDY GIRL OVERDOSE -OVERTURE-
    621233, # 卡片战斗先导者 15周年纪念PV
    621258, # Underdog
    621521, # 斗龙战士之星印罗盘
    623063, # それいけ！アンパンマン パンタンと約束の星
    623179, # 「ray 超かぐや姫！Version」MV
    623228, # 你与烟花与约定
    623351, # 最強王図鑑～The Ultimate Tournament～ 特別編 テッペン決めようか！
    624688, # 铸日于极夜
    624836, # 新幹線変形ロボ シンカリオン 特別ダイヤ版
    624848, # 海馬成長痛 × Mass Destruction -Reload- マッシュアップMV
    625109, # تحديث_يفهمك
    625144, # LUCA
    625195, # Le Jardin Rossini
    625355, # 屁屁侦探 第十季
    626168, # 黑白心弈
    628184, # 【动画MV】人生不易部！「Dou-Da? DOING!」【生如百戏难！LOVELIVE! 青鸟】
    628580, # 刹那芳华
    628605, # 直到蓝天重现
    628619, # 灰烬Refusion：楔
    628621, # 过年者联盟之新春赛马
    628629, # 魔物料理人
    628631, # 人生列车
    628635, # 再一次的“初见”
    630164, # 澈底对你成瘾
    630861, # あるふぁYOU
    631617, # 堪解人间
    631619, # 辟浪
    632064, # 「边狱巴士公司」3周年纪念动画
    632198, # 誰も見てない夢を見ろ
    632361, # The Mountain, The Moon Cave and The Sad God
    633363, # ファッションビート
    633711, # プラノサウルス ガチコセイブツ部
    634029, # Gamer Girls Music Video
    634216, # 无限∞动画
    634276, # 哈羅德-Harold Godwinson-
    634877, # いのちになる少女
    635233, # こんなこいるかな
    635290, # 板取小学校 閉校式
    635806, # 我的路在前方
    635912, # 少女与战车：缎带武士 样片
    636048, # 反斗小王子 第29季
    636328, # 絶対逆転バンカイザー
    636423, # data-cosm [n°1]
    636546, # 《机动武斗传G高达》30周年纪念影片
    637293, # 【グッド！モーニング】オープニングアニメーション
    637339, # 北斗神拳 拳王军杂兵们的挽歌 第二季
    637408, # うそ探偵トマント
    638082, # ほっかいどうぶつ
    638186, # AnimeCanvas コマーシャルフィルム
    638437, # 管制塔より
    638440, # 神姬PROJECT 10周年纪念PV（2026）
    638511, # 《绝区零》2025 FES 动画CM | 丽都闪耀时
    638765, # 迷宫塔 6卷发售纪念PV
    638799, # 【动画】【百万现场！】「飛べない僕は泳いだ」特別MV【偶像大师】
    638995, # 拯救替身千金的是冷酷无情冰之王子的爱
    639087, # 瞬発的に恋しよう
    639405, # 涟漪看到些什么
    639440, # 11周年庆群像献礼片《天命归来》
    639563, # 【君を紡ぐ】アニメPV
    639899, # これは二度目で最後の初恋
    640588, # 书面痕迹
    641640, # 椿町ファミリーの府中町に超夢中
    641775, # 台风眼 动态漫
    642404, # 《洛克王国：世界》概念动画短片 | 王国的夏日清风
    642552, # 花筏
    642590, # 蔚蓝档案 7th PV
    643823, # HoYoHoYoにしてあげる♪
    643829, # 『逆転オセロニア』オセロニアンの祭典 10th Anniversary ヴァイセ超化開放PV
    644242, # 下一秒
    644723, # Side Quest King (KISAI remix) feat. 初音ミク
    645346, # 風のアンセム feat. suis from ヨルシカ
    646025, # Voyager One
    646043, # 《重返未来：1999》三周年纪念动画：隙光掠影
    646464, # 我的英雄学院 I am a hero too
    646584, # 尼科罗
    647988, # STAR TRAIL
    651247, # Sehrlandiya: qahramonlik missiyasi
    651807, # Skin Flick
    651872, # パンの赤ちゃん
    653435, # 亲爱的Fin.
    653597, # 第十三屆動畫支援計劃
    654389, # 风滚草
    655393, # 最后的春天
    655650, # 《异环》角色短片
    656105, # 该死的告白日 宣传影片
    658093, # 抓周
    658869, # NAFCAオリジナルアニメ【ほくとと影マル】
    659007, # スト6 Year 4キャラクターPV
    659008, # 「Return トゥ 頭（ヘッド）」Music Video
    659091, # オロチ -Seventh Echoes-
    659100, # Kawaii Lore: Moko & Pyle
    659252, # error403
    659664, # 中国传媒大学2026届动画与数字艺术学院毕业设计联展——动画作品展
    659680, # 「BE MY STAR」MV Full Ver. | 勝利の女神：NIKKE
    659686, # トミカとトム シーズン2
    659810, # 四川美术学院影视动画学院2026届动画专业毕业设计展映
    660115, # 「動物探偵ミア」シリーズ PV
    660385, # とらぶるだいあり〜・ごーるど ムービー版HDリマスター
    661083, # 伝えたい想いのそばに 碧い海商店街
    661948, # MAPPA 15th Anniversary Movie
    662006, # 暗芝居 第十七季
    662130, # 动画【电锯人】手机游戏 OP Movie
    662482, # 《鸣潮》巡回演唱会「致予新世界」预告动画
    663613, # 烏
    663827, # あびすいんざわーるど
    663884, # ホーミー・タイッ!!
    663886, # 起死開戦
    663898, # 「BanG Dream! 交织的乐章」动画CM
    664060, # AKANE On My Mind〜饅頭こわい
    664407, # 斯大林战甲
    664702, # パッチワーク・ヒーロー/緋八マナ
    664773, # Re:PRISM/WeatherPlanet【official】
    664874, # ꕤ「FBKINGDOM STORY」アニメーショントレーラー ꕤ
    665218, # 看家
    668590, # ホウキボシ
    668623, # その化学は、すべてに愛をつなぐ
    668672, # 少年们，跨过蟑螂成为男人吧！
    668858, # 【初音未来】Mag1c ⭐
    668862, # SPARK-星火 feat. piapro characters
    668916, # 丸淡！晕车了口牙！！
    670845, # ⚡一?飞⚡?⚡虫?天⚡
    675373, # 出发吧，北极！
    675400, # 魔法少女太多了！！！
    679496, # 「甲铁城的卡巴内利 无名烂漫」手办发售纪念影片
    680590, # 【绝区零】唱片争夺战！
    687636, # 仿生天使会梦见赛博恶魔吗？
    687660, # ROSE. ‒ Vocal : ロス MUSIC VIDEO【Zenless Zone Zero】
    689021, # 「Fate/Grand Order」11th Anniversary Movie -Cosmos in the Lostbelt-
    690181, # 2026届北京电影学院动画学院优秀毕业作品暨联合创作汇报展
    692000, # 【1巻発売記念】『ゴールデンファントム』短編アニメーション
    692038, # 火柴人 VS 游戏设计
    692071, # 我喜欢我自己 MV
    692303, # 「Astral lamp」MV
    692307, # 人肉盾牌
    695318, # きゃぴ
    695700, # 「Fate/Grand Order展 -星見の回廊-」オープニングシアター
    696005, # 【アニメーションMV】燦然燃焼 - Omaru Polka（Original）
    696007, # コンティニュー - NEE
    696644, # KA Esuma文库《草原的光辉》动画CM
    696681, # 【共鳴のアルカソング】スポットPV
    696806, # Mulu
]

[sync]
api_concurrency = 3
request_timeout_seconds = 20
max_retries = 3
