[filters]
excluded_subject_ids = [
    184017, # Bangumi Wiki 动画测试用沙盘
]
auto_excluded_subject_ids = [
    332677, # 贝里琉岛 -乐园的格尔尼卡
    363612, # 沙盒
    375983, # 光遇·双星 暮星篇
    414861, # Future Kid Takara
    460178, # Krapopolis Season 3
    461307, # 怪盗皇后的优雅假期
    471868, # 剧场版 歌之王子殿下 TABOO NIGHT XXXX
    473414, # 永远的大和号 REBEL3199 第四章 水色的少女
    473415, # 永远的大和号 REBEL3199 第五章 白热的银河大战
    473416, # 永远的大和号 REBEL3199 第六章 碧蓝迷宫
    487782, # 新劇場版☆ケロロ軍曹 復活して速攻地球滅亡の危機であります！
    494044, # 电影 小鲨鱼去郊游
    496945, # 如果烧陶的话也做个马克杯吧 剧场版
    501198, # 怪兽世界征服
    501729, # 剧场版 魔法科高校的劣等生 四叶继承篇
    505562, # 剧场版 物怪 蛇神
    507943, # たべっ子どうぶつ THE MOVIE
    523889, # 全力兔子 第二季
    525084, # KING OF PRISM -Your Endless Call- み～んなきらめけ！プリズム☆ツアーズ
    529240, # 屁屁侦探 第九季
    530309, # 最强王图鉴 ～The Ultimate Tournament～
    531576, # 不忍！加密忍者咲耶 叁之卷
    532053, # 地球大好き！きっくん
    532772, # クマーバ シーズン3
    534568, # 呜莓猫猫
    534907, # IDOLiSH7-偶像星愿- 剧场总集篇 前篇
    538402, # 女同太空公主
    540904, # 忘星のヴァリシア 第二章：群青
    541037, # 涩谷♡八 第三部分
    541423, # 忍者乱太郎 第33季
    541539, # AS ONE
    541961, # 大耳鼠 惠理大人的好运
    542125, # 面包超人 恰彭的英雄！
    542812, # 废世界
    544236, # 鬼太郎 我最喜欢的历代咯咯咯
    544872, # 竹轮战纪～用我的可爱来侵略地球～
    545844, # 电影 角落小伙伴 天空王国与两位小伙伴
    546442, # 噗尼轮轮 噗尼3
    547873, # MUZIK TIGER In the Forest
    548858, # 角落小伙伴 这里让人好安心
    549153, # 辉夜大小姐想让我告白～回忆精选～
    549288, # 岛津制作所 创业150周年纪念动画
    549375, # ノモの国
    550457, # YouTu喵 第三季动画剧集
    550487, # Go! Go! Vehicle Zoo 交通工具明星篇
    552670, # 烟囱小镇的普佩 〜约定的钟楼〜
    553366, # 《饿狼传说：群狼之城》萨尔瓦多·加纳奇 x 大张正己 特别MV
    554391, # 乐高幻影忍者：神龙崛起 第三季
    554553, # 【#ホロアース】アニメPV「さあ、あなたのもう ひとつのセカイへ」
    555159, # 《崩坏：星穹铁道》二周年特别动画：「不虚此行」
    555204, # 蔚蓝档案 6th PV
    555683, # IDOLiSH7-偶像星愿- 剧场总集篇 后篇
    556075, # 地球のラテール
    556862, # 封灵特优生
    556863, # 人ってただの筒じゃないですか
    557539, # Break Me Up, Break Me Down
    557644, # 好きを、もっと好きになる。
    558645, # 星街すいせい(official) MUSIC VIDEO
    559238, # 龙之心 灵界探访记
    559674, # 学校では教えてくれない大切なこと 整理整頓編
    559758, # 浮生一戏
    559967, # 特装作业勇者
    559998, # 捡了个佛
    560282, # feel like
    561267, # 奥利维亚与无声震波
    561272, # Planètes
    561622, # 她在时空尽头
    561642, # 儿子
    561787, # 小哥斯拉的逆袭 系列最新作
    561791, # 《重返未来：1999》二周年纪念动画：旧世新生
    561920, # Wylde Pak
    561932, # DAY DREAM
    562014, # 《星际宝贝史迪奇》宣传动画
    562099, # 谁是窃书之人
    562129, # 双猫成行
    562148, # 螺丝人生
    562601, # 鱼之死
    562605, # 我不在的明天
    563367, # 乐高梦境城猎人 第三季：进入二次元游戏
    564268, # 偶像活动！纪念舞台～闪耀的组合杯～
    564288, # 海医—柳刀霹雳—
    564314, # 週刊ラノべアニメ
    564328, # Shadowverse: Worlds Beyond 动画PV
    564362, # Women Wearing Shoulder Pads
    564373, # 当哒当 邪视
    564419, # 米奇妙妙屋+
    564506, # トミカとトム
    564509, # 『さうのあっ！』2巻発売記念 アニメPV
    564847, # 混乱的要求
    564849, # 尽诸东流
    564850, # 阿尔丘的下午
    564884, # 星蚀
    564885, # 倒带时光
    564886, # 花花花
    564888, # 猴子和小偷
    564900, # 乐高幻影忍者 传奇：魔兽之地
    565007, # 鯨を夢む
    565180, # 鉴因缘
    565253, # 猴子捞月
    565255, # 逆旅
    565256, # 影的告白
    565266, # 霉
    565271, # 极速吗喽
    565277, # 蝉鸣
    565279, # 李子
    565284, # 姥爷的邮票
    565325, # ネコこのゴロ～天下統一編～
    565361, # Re0 IF线
    565362, # 中国传媒大学动画与数字艺术学院 2021级动画专业毕业/联创展
    565794, # F/ACE「F/ACE OFF」｜Music Video
    566453, # 哪吒之三宝闯世运
    567070, # 《偶像大师 百万现场 剧场时光》8周年特别PV
    567520, # 【无职转生同人动画】血契之约
    567900, # 夜光溯明
    568292, # 葫芦兄妹
    568294, # 金刚葫芦妹
    568674, # 混乱的海市蜃楼
    570330, # 怪物弹珠 DEADVERSE RELOADED
    573465, # 新机动战记高达W -Operation 30th-
    573700, # 阿兹特克蝙蝠侠：帝国冲突
    574525, # 【ネタバレ注意】BOOM！THE GHOST！スペシャルアニメーション│ 勝利の女神：NIKKE
    575899, # 「Fate/Grand Order」十周年纪念映像
    576103, # 信息素说我们不可能 动态漫
    576265, # 学校では教えてくれない大切なこと 時間の使い方編
    576283, # 小魔女DoReMi嘉年华!! 悠闲之旅篇
    576310, # ただいまを返す旅
    576343, # ほっぺちゃん ～サン王国と黒ほっぺ団の秘密～
    576669, # 绽放的巴黎之星
    578275, # 後朝の花雪
    580446, # 越辙而行
    580762, # 住在神奈川的精灵
    581250, # 螳螂
    581987, # JOCHUM 第2季
    582598, # ねずみくんのチョッキ
    582915, # 涩谷♡八 第四部分
    583138, # 「エガクミライ」アニメーションMV
    583528, # 碧蓝航线 8周年纪念动画PV
    583581, # 辛普森一家 第37季
    583732, # チューニング
    583974, # 小泉八云的怪谈世界
    584377, # LA PANTHÈRE DE CARTIER
    585031, # ReGLOSS 'アワータイムイエロー' OFFICIAL MV
    585457, # 森林家族 芙蕾雅的奇妙时光
    586186, # generAIdoscope：ジェネレイドスコープ
    587666, # 如月而至金拱门
    588026, # アニラとココラ
    588231, # 「LIMIT ZERO BREAKERS」世界観PV世界は救わない。自らを救う物語。(Full ver.)
    588612, # 2200年猫之国日本
    588875, # 内気な少女の放課後セイカツ
    588877, # ソウルワーカー、闇落ち
    589793, # うそ探偵トマント ベジフル“プチっ”と情報編
    590629, # Mafiosa
    591455, # 雀魂 X 银魂 联动动画PV
    592129, # 起始点
    593226, # 莱尔校长火力全开三部曲
    596843, # 聖女なのに国を追い出されたので、崩壊寸前の隣国へ来ました シーズン2
    596930, # 梭子鱼船长的船
    598053, # 微かな夕阳 / 魔法少女ホロウィッチ！
    599919, # Run Run Lantern
    600956, # 「人生讚歌」Official Music Video
    601763, # 你还是不懂群马～令和版～
    602943, # 宇宙涅槃
    604330, # 《藤本树17-26》Part-1
    604331, # 《藤本树17-26》Part-2
    605312, # おしり前マン〜復活のおしり前帝国〜
    607043, # 小3阿贝 QQ小芝麻
    609741, # バトルヒロインの日常～愛天使世紀ウェディングアップル～
    609915, # Tokyo Nightscape
    610350, # 黄金神威 札幌啤酒工厂篇 前篇
    610359, # 黄金神威 札幌啤酒工厂篇 后篇
    610612, # 三月凛冬
    611074, # Saudi Arabia National Day #95 Animation
    611768, # 电影秘密的偶像公主
    612697, # 铠真传 武士军团 第2部分
    613025, # 迷失的万圣节：十年之后
    613379, # そろ谷のけいばっち シーズン2
    613380, # そろ谷のけいばっち シーズン3
    613815, # 奔向太阳
    615446, # 电影蜡笔小新：奇奇怪怪！我的妖怪假期
    616378, # 小鲨鱼去郊游 第二季
    616383, # 《新世纪福音战士》30周年纪念特别放映
    616392, # 【汐塔】《云海逐鲸》
    616616, # 百姓贵族 第四季
    617004, # CHOPPER’s
    617321, # 今日をしるして
    617947, # 为了共同闪耀的明天
    618661, # ゲルぴよ
    619052, # 做得很好！名作君 完全新作
    619136, # 能登半島復興応援企画
    619321, # 「花の芥 -Re;bloom-」 告知アニメPV
    619447, # シルベ
    619911, # 托尼托尼·乔巴
    620064, # 如果烧陶的话也做个马克杯吧 二番窑 剧场总集篇
    620111, # 音乐 完全版
    620410, # THE RUN.
    620584, # 「Q.E.D.」MV
    620741, # 黑猫警长——人工智能安全篇
    620918, # NEEDY GIRL OVERDOSE -OVERTURE-
    621233, # 卡片战斗先导者 15周年纪念PV
    621258, # Underdog
    621521, # 斗龙战士之星印罗盘
    621662, # 上帝怯场
    622354, # One Last Wish - DADA GAUGUIN
    623063, # それいけ！アンパンマン パンタンと約束の星
    623179, # 「ray 超かぐや姫！Version」MV
    623228, # 你与烟花与约定
    623351, # 最強王図鑑～The Ultimate Tournament～ 特別編 テッペン決めようか！
    623353, # Thomas & Friends: Sodor Sings Together
    624688, # 铸日于极夜
    624836, # 新幹線変形ロボ シンカリオン 特別ダイヤ版
    624848, # 海馬成長痛 × Mass Destruction -Reload- マッシュアップMV
    625026, # Winx Club: The Magic is Back
    625109, # تحديث_يفهمك
    625144, # LUCA
    625195, # Le Jardin Rossini
    625355, # 屁屁侦探 第十季
    625419, # 反骨女配绝不走剧情
    626168, # 黑白心弈
    628184, # 【动画MV】人生不易部！「Dou-Da? DOING!」【生如百戏难！LOVELIVE! 青鸟】
    628580, # 刹那芳华
    628605, # 直到蓝天重现
    628619, # 灰烬Refusion：楔
    628621, # 过年者联盟之新春赛马
    628629, # 魔物料理人
    628631, # 人生列车
    628635, # 再一次的“初见”
    630164, # 澈底对你成瘾
    630861, # あるふぁYOU
    631050, # Minnie's Bow-Toons: Pet Hotel
    631617, # 堪解人间
    631619, # 辟浪
    632064, # 「边狱巴士公司」3周年纪念动画
    632197, # 「きらめく絆創膏」 Music Video
    632198, # 誰も見てない夢を見ろ
    632361, # The Mountain, The Moon Cave and The Sad God
    632684, # Summertime girl with Awesome robot
    633363, # ファッションビート
    633711, # プラノサウルス ガチコセイブツ部
    634029, # Gamer Girls Music Video
    634216, # 无限∞动画
    634276, # 哈羅德-Harold Godwinson-
    634877, # いのちになる少女
    634884, # ロクデナシ「雨景色」Official Music Video
    635233, # こんなこいるかな
    635290, # 板取小学校 閉校式
    635806, # 我的路在前方
    635912, # 少女与战车：缎带武士 样片
    636047, # おじゃる丸 第28シリーズ
    636048, # 反斗小王子 第29季
    636328, # 絶対逆転バンカイザー
    636423, # data-cosm [n°1]
    636546, # 《机动武斗传G高达》30周年纪念影片
    637293, # 【グッド！モーニング】オープニングアニメーション
    637339, # 北斗神拳 拳王军杂兵们的挽歌 第二季
    637408, # うそ探偵トマント
    638082, # ほっかいどうぶつ
    638186, # AnimeCanvas コマーシャルフィルム
    638437, # 管制塔より
    638440, # 神姬PROJECT 10周年纪念PV（2026）
    638511, # 《绝区零》2025 FES 动画CM | 丽都闪耀时
    638765, # 迷宫塔 6卷发售纪念PV
    638799, # 【动画】【百万现场！】「飛べない僕は泳いだ」特別MV【偶像大师】
    638995, # 拯救替身千金的是冷酷无情冰之王子的爱
    639087, # 瞬発的に恋しよう
    639405, # 涟漪看到些什么
    639440, # 11周年庆群像献礼片《天命归来》
    639563, # 【君を紡ぐ】アニメPV
    639899, # これは二度目で最後の初恋
    640588, # 书面痕迹
    640702, # For the Destiny
    640929, # 海底小纵队：海啸大危机
    640943, # 海底小纵队 第十季
    641640, # 椿町ファミリーの府中町に超夢中
    641775, # 台风眼 动态漫
    642404, # 《洛克王国：世界》概念动画短片 | 王国的夏日清风
    642552, # 花筏
    642590, # 蔚蓝档案 7th PV
    643823, # HoYoHoYoにしてあげる♪
    643829, # 『逆転オセロニア』オセロニアンの祭典 10th Anniversary ヴァイセ超化開放PV
    644242, # 下一秒
    644723, # Side Quest King (KISAI remix) feat. 初音ミク
    645346, # 風のアンセム feat. suis from ヨルシカ
    646001, # Porque Hoje é Sábado
    646005, # Somnia
    646008, # Ostrich
    646009, # Tigre
    646023, # Cão Sozinho
    646025, # Voyager One
    646043, # 《重返未来：1999》三周年纪念动画：隙光掠影
    646464, # 我的英雄学院 I am a hero too
    646584, # 尼科罗
    647194, # 斗罗大陆2绝世唐门 第7季 · 动态漫
    647988, # STAR TRAIL
    651247, # Sehrlandiya: qahramonlik missiyasi
    651807, # Skin Flick
    651872, # パンの赤ちゃん
    653435, # 亲爱的Fin.
    653591, # 第十二屆動畫支援計劃
    653597, # 第十三屆動畫支援計劃
    654389, # 风滚草
    655393, # 最后的春天
    655650, # 《异环》角色短片
    656105, # 该死的告白日 宣传影片
    658093, # 抓周
    658869, # NAFCAオリジナルアニメ【ほくとと影マル】
    658935, # 우렁강도
    659007, # スト6 Year 4キャラクターPV
    659008, # 「Return トゥ 頭（ヘッド）」Music Video
    659091, # オロチ -Seventh Echoes-
    659100, # Kawaii Lore: Moko & Pyle
    659252, # error403
    659664, # 中国传媒大学2026届动画与数字艺术学院毕业设计联展——动画作品展
    659680, # 「BE MY STAR」MV Full Ver. | 勝利の女神：NIKKE
    659686, # トミカとトム シーズン2
    659701, # 汪汪队立大功 第十二季
    659810, # 四川美术学院影视动画学院2026届动画专业毕业设计展映
    660115, # 「動物探偵ミア」シリーズ PV
    660385, # とらぶるだいあり〜・ごーるど ムービー版HDリマスター
    661083, # 伝えたい想いのそばに 碧い海商店街
    661948, # MAPPA 15th Anniversary Movie
    662006, # 暗芝居 第十七季
    662130, # 动画【电锯人】手机游戏 OP Movie
    662482, # 《鸣潮》巡回演唱会「致予新世界」预告动画
    663613, # 烏
    663827, # あびすいんざわーるど
    663858, # Annecy Festival 2025 Partners Trailer
    663884, # ホーミー・タイッ!!
    663886, # 起死開戦
    663898, # 「BanG Dream! 交织的乐章」动画CM
    664060, # AKANE On My Mind〜饅頭こわい
    664407, # 斯大林战甲
    664702, # パッチワーク・ヒーロー/緋八マナ
    664773, # Re:PRISM/WeatherPlanet【official】
    664874, # ꕤ「FBKINGDOM STORY」アニメーショントレーラー ꕤ
    665218, # 看家
    666606, # 欢乐海鹦岛 第三季
    668142, # 海街日记
    668590, # ホウキボシ
    668623, # その化学は、すべてに愛をつなぐ
    668672, # 少年们，跨过蟑螂成为男人吧！
    668776, # 魔法可爱
    668858, # 【初音未来】Mag1c ⭐
    668862, # SPARK-星火 feat. piapro characters
    668916, # 丸淡！晕车了口牙！！
    670845, # ⚡一?飞⚡?⚡虫?天⚡
    675373, # 出发吧，北极！
    675400, # 魔法少女太多了！！！
    679496, # 「甲铁城的卡巴内利 无名烂漫」手办发售纪念影片
    680590, # 【绝区零】唱片争夺战！
    686376, # 少林邦布足球赛
    687636, # 仿生天使会梦见赛博恶魔吗？
    687660, # ROSE. ‒ Vocal : ロス MUSIC VIDEO【Zenless Zone Zero】
    689021, # 「Fate/Grand Order」11th Anniversary Movie -Cosmos in the Lostbelt-
    690181, # 2026届北京电影学院动画学院优秀毕业作品暨联合创作汇报展
    690185, # 2025·北京电影学院动画学院优秀毕业展
    691172, # 荆棘鸟
    692000, # 【1巻発売記念】『ゴールデンファントム』短編アニメーション
    692036, # 火柴人 VS APP权杖
    692038, # 火柴人 VS 游戏设计
    692071, # 我喜欢我自己 MV
    692303, # 「Astral lamp」MV
    692307, # 人肉盾牌
    695318, # きゃぴ
    695700, # 「Fate/Grand Order展 -星見の回廊-」オープニングシアター
    696005, # 【アニメーションMV】燦然燃焼 - Omaru Polka（Original）
    696007, # コンティニュー - NEE
    696644, # KA Esuma文库《草原的光辉》动画CM
    696681, # 【共鳴のアルカソング】スポットPV
    696806, # Mulu
]

[sync]
api_concurrency = 3
request_timeout_seconds = 20
max_retries = 3
